scalar DateTime

input DateRangeInput {
  from: DateTime
  to: DateTime
}

# Define o tipo para os filtros que podemos receber
input DiariasFilters {
  dateRange: DateRangeInput
  departmentCode: String
  status: String
  processNumber: String
  employee: String
}

input DiariasFiltersOptions {
  dateRange: DateRangeInput
  departmentCode: String
  status: String
  processNumber: String
  employee: String
}

input DiariasTableFilters {
  grantedDate: String
  grantedAmount: String
  departmentCode: String
  processNumber: String
  employee: String
  status: String
}

# Dados para os KPIs
type KpiData {
  totalAprovado: Float
  totalConcedido: Float
  totalDiarias: Int
}

# Dados para o gráfico de Top Orgaos
type GastoOrgaoDiaria {
  name: String
  total: Float
}

type GastoFuncionarioDiaria {
  name: String
  total: Float
}

# Dados para o gráfico de Gasto Mensal
type GastoMesDiaria {
  name: String
  total: Float
}

type DiariasCharts {
  GastoOrgaoDiaria: [GastoOrgaoDiaria]
  GastoFuncionarioDiaria: [GastoFuncionarioDiaria]
  GastoMesDiaria: [GastoMesDiaria]
}

type Diarias {
  expenseType: String
  paymentNumber: String
  paymentDate: String
  settlementNumber: String
  fiscalDoc: String
  commitmentNumber: String
  employee: String
  employeeDoc: String
  limitDeliveryDate: String
  limitSpendDate: String
  requestDate: String
  history: String
  amountRequested: Float
  approvalDate: String
  amountApproved: Float
  disallowedDate: String
  disallowedValue: Float
  defaultDate: String
  defaultValue: Float
  grantedDate: String
  grantedValue: Float
  canceledDate: String
  canceledValue: Float
  grantedAmount: Float
  balance: Float
  entityName: String
  departmentCode: String
  budgetUnitCode: String
  functionCode: String
  subFunctionCode: String
  programCode: String
  actionCode: String
  expensePlanCode: String
  subElementCode: String
  resourceSourceCode: String
  baseDate: String
  finalAccountDate: String
  delayDays: String
  processNumber: String
  advanceNumber: String
  id: ID
  status: String
}

# O tipo Diaria para a tabela
type DiariaTable {
  departmentCode: String
  processNumber: String
  employee: String
  grantedAmount: Float
  grantedDate: String
  status: String
}

type FilterOption {
  value: String
  label: String
}

type FilterOptionsDiaria {
  departmentCode: [FilterOption]
  status: [FilterOption]
  processNumber: [FilterOption]
  employee: [FilterOption]
}

# A Query principal
type Query {
  getDiarias(filters: DiariasFilters): [Diarias]
  getDiariasTable(
    limit: Int
    offset: Int
    sortBy: String
    sortDirection: String
    filters: DiariasFilters
    tableFilters: DiariasTableFilters
  ): [DiariaTable]

  getDiariasTableCount(
    filters: DiariasFilters
    tableFilters: DiariasTableFilters
  ): Int

  getDiariasLastUpdate: DateTime
  getDiariasKpi(filters: DiariasFilters): KpiData
  getDiariasCharts(filters: DiariasFilters): DiariasCharts
  getDiariasFiltersOptions(filters: DiariasFiltersOptions): FilterOptionsDiaria
}
